name: ServiceNow DevOps Change

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Build completed"
  ServiceNowDevOpsChange:
    needs: build
    runs-on: ubuntu-latest
    name: 'ServiceNow DevOps Change'

    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v5.1.0
        with:
          devops-integration-token: rBCJr4BU2DCzBjojXBhevvEyjJqXGARE
          instance-url: https://dev296263.service-now.com
          tool-id: 6106c20b932203503f5a30dcebba1019
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow DevOps Change'
