name: ServiceNow DevOps Change

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Build completed"
  ServiceNowDevOpsChange:
    needs: build
    runs-on: ubuntu-latest
    name: 'ServiceNow DevOps Change'

    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v5.1.0
        with:
          devops-integration-token: TgaG2rBxlsH09FiEmkah0nM1xJyPuMZS
          instance-url: https://dev296263.service-now.com
          tool-id: 902c82cb936203503f5a30dcebba104f
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow DevOps Change'
